# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Antonio Garc√≠a, frontend developer
email: agl0809@gmail.com
description: Biography
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://agl0809.github.io" # the base hostname & protocol for your site
twitter_username: agl0809
github_username:  agl0809

# Build settings
markdown: kramdown
